# Generated by Django 3.0.3 on 2020-04-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookfarm', '0002_hello'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hello',
        ),
    ]
